// ============================================================
// worker/src/adapters/email.ts
// Email channel adapter — SMTP via Nodemailer.
//
// DESIGN:
//   Pure send function, zero BullMQ coupling.
//   Extracted from email.worker.ts so it can be used by any
//   worker that needs to send email without duplicating the
//   transport setup and from-address resolution logic.
//
// USAGE:
//   import { sendEmailDirect } from "../adapters/email";
//   await sendEmailDirect({ to, subject, html });
// ============================================================

import nodemailer, { type Transporter } from "nodemailer";
import { logger } from "../logger";

const log = logger.child({ module: "adapter.email" });

export interface EmailChannelPayload {
  to: string | string[];
  subject: string;
  /** Pre-rendered HTML string */
  html: string;
  /** Plain-text fallback — auto-generated by Nodemailer if omitted */
  text?: string;
  replyTo?: string;
  /** Overrides SMTP_FROM for this specific send */
  from?: string;
}

// ---------------------------------------------------------------------------
// Transporter singleton — lazily initialised, shared across worker jobs
// ---------------------------------------------------------------------------
let _transporter: Transporter | null = null;

export function getTransporter(): Transporter {
  if (_transporter) return _transporter;

  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT ?? "587", 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    throw new Error(
      "[adapter.email] Missing SMTP config. Set SMTP_HOST, SMTP_USER, SMTP_PASS."
    );
  }

  _transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  });

  return _transporter;
}

function resolveFrom(override?: string): string {
  const from = override ?? process.env.SMTP_FROM;
  if (!from) {
    throw new Error(
      "[adapter.email] No sender address. Set SMTP_FROM or pass `from` in the payload."
    );
  }
  return from;
}

// ---------------------------------------------------------------------------
// Primary export
// ---------------------------------------------------------------------------

/**
 * Sends an email directly via SMTP. Throws on failure — let the caller
 * (worker) handle retries via BullMQ.
 */
export async function sendEmailDirect(payload: EmailChannelPayload): Promise<void> {
  const transporter = getTransporter();
  const from = resolveFrom(payload.from);

  await transporter.sendMail({
    from,
    to: Array.isArray(payload.to) ? payload.to.join(", ") : payload.to,
    subject: payload.subject,
    html: payload.html,
    text: payload.text,
    replyTo: payload.replyTo,
  });

  log.info(
    { event: "email.sent", subject: payload.subject },
    "Email sent"
  );
}
