// ============================================================
// src/lib/email.ts
// Foundry Email Layer — Nodemailer/SMTP transport.
//
// DESIGN:
//   Two call sites are exposed:
//
//   1. sendEmail(payload)    — Direct synchronous send via SMTP.
//      Use for CRITICAL notifications: password resets, payment
//      failure alerts, OTPs, etc. Awaiting this guarantees the
//      email was accepted by the SMTP server before returning.
//
//   2. enqueueEmail(payload) — Async BullMQ job (EMAIL_SEND queue).
//      Use for NON-CRITICAL transactional emails: welcome emails,
//      receipts, digests. Fire-and-forget — the worker handles
//      delivery with 5 retry attempts + exponential backoff.
//      Exhausted jobs automatically move to EMAIL_DLQ.
//
// CONFIGURATION (.env):
//   SMTP_HOST   — e.g. "smtp.resend.com" or "smtp.mailgun.org"
//   SMTP_PORT   — 587 (STARTTLS, default) or 465 (SSL)
//   SMTP_USER   — provider username / API key username
//   SMTP_PASS   — provider password / API key
//   SMTP_FROM   — default From address, e.g. "App <no-reply@app.com>"
//
// TEMPLATES:
//   Use @react-email/render to pre-render JSX templates to HTML
//   strings BEFORE calling sendEmail or enqueueEmail. The email
//   layer accepts plain strings — no React dep required here.
//
//   Example:
//     import { render } from "@react-email/render";
//     import { WelcomeEmail } from "@/emails";
//     const html = await render(<WelcomeEmail name={user.name} />);
//     await enqueueEmail({ to: user.email, subject: "Welcome!", html });
//
// OBSERVABILITY:
//   All sends are logged via the structured Pino logger.
//   The `to` address is redacted in production log lines.
// ============================================================

import "server-only";
import nodemailer, { type Transporter } from "nodemailer";
import { logger } from "@/lib/logger";
import { enqueue, QUEUES } from "@/lib/queue";

const log = logger.child({ module: "email" });

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface EmailPayload {
  /** Recipient(s). Single address or array for bulk. */
  to: string | string[];
  subject: string;
  /** Pre-rendered HTML string. Use @react-email/render before calling. */
  html: string;
  /** Plain-text fallback. Auto-generated by Nodemailer if omitted. */
  text?: string;
  /** Reply-To header. */
  replyTo?: string;
  /** Overrides SMTP_FROM for this specific send. */
  from?: string;
}

export type EmailResult =
  | { ok: true; messageId: string }
  | { ok: false; error: string };

// ---------------------------------------------------------------------------
// Transporter singleton
// Lazily initialised at first use — safe during Next.js build time.
// ---------------------------------------------------------------------------
let _transporter: Transporter | null = null;

function getTransporter(): Transporter {
  if (_transporter) return _transporter;

  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT ?? "587", 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!host || !user || !pass) {
    throw new Error(
      "[email] Missing SMTP configuration. Set SMTP_HOST, SMTP_USER, and SMTP_PASS in your .env file."
    );
  }

  _transporter = nodemailer.createTransport({
    host,
    port,
    // port 465 → implicit TLS; 587 → STARTTLS (upgrade after connection)
    secure: port === 465,
    auth: { user, pass },
  });

  return _transporter;
}

function getFrom(override?: string): string {
  const from = override ?? process.env.SMTP_FROM;
  if (!from) {
    throw new Error(
      "[email] No sender address. Set SMTP_FROM in your .env or pass `from` in the payload."
    );
  }
  return from;
}

// ---------------------------------------------------------------------------
// sendEmail — synchronous direct send
//
// Use this on the CRITICAL PATH where you must know the email was
// accepted before proceeding (e.g. password reset, OTP delivery).
// ---------------------------------------------------------------------------
export async function sendEmail(payload: EmailPayload): Promise<EmailResult> {
  let transporter: Transporter;

  try {
    transporter = getTransporter();
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    log.error({ event: "email.config_error", error }, "Email transporter configuration failed");
    return { ok: false, error };
  }

  const from = (() => {
    try {
      return getFrom(payload.from);
    } catch (err) {
      return err instanceof Error ? err.message : String(err);
    }
  })();

  // If getFrom() returned an error string (threw), bail early.
  if (from.startsWith("[email]")) {
    return { ok: false, error: from };
  }

  try {
    const info = await transporter.sendMail({
      from,
      to: Array.isArray(payload.to) ? payload.to.join(", ") : payload.to,
      subject: payload.subject,
      html: payload.html,
      text: payload.text,
      replyTo: payload.replyTo,
    });

    log.info(
      {
        event: "email.sent",
        messageId: info.messageId,
        subject: payload.subject,
        // `to` is redacted by the Pino redact config in logger.ts
        to: payload.to,
      },
      "Email sent successfully"
    );

    return { ok: true, messageId: info.messageId as string };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    log.error(
      { event: "email.failed", subject: payload.subject, to: payload.to, error },
      "Email send failed"
    );
    return { ok: false, error };
  }
}

// ---------------------------------------------------------------------------
// enqueueEmail — async BullMQ delivery
//
// Use this for NON-CRITICAL transactional emails. The job is processed
// by the worker (worker/src/workers/email.worker.ts) with:
//   - 5 retry attempts
//   - Exponential backoff starting at 2 000ms
//   - Automatic DLQ (email_dlq) on exhaustion
//
// Returns the BullMQ Job object. In most cases you can ignore the return
// value — the worker will log success/failure and handle retries.
// ---------------------------------------------------------------------------
export async function enqueueEmail(payload: EmailPayload) {
  const job = await enqueue(QUEUES.EMAIL_SEND, payload, { attempts: 5 });

  log.info(
    {
      event: "email.enqueued",
      jobId: job.id,
      subject: payload.subject,
      to: payload.to,
    },
    "Email job enqueued"
  );

  return job;
}
